name: AWS Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean -B package -DskipTests --file pom.xml
    
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v2
      with:
        name: jar-artifact
        path: target/test-env.jar
  
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    - name: Download JAR artifact
      uses: actions/download-artifact@v2
      with:
        name: jar-artifact
        path: target/

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v13
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }} #This is referred from Github Secrets
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} #This is referred from Github Secrets
        use_existing_version_if_available: true
        application_name: tf-spring #Application name we created in Elastic BeanStalk / Terraform
        environment_name: tf-spring-env #Environment name we created in Elastic BeanStalk / Terraform
        version_label: ${{github.SHA}}
        region: us-east-1 #VERY IMPORTANT: AWS Region where initially Applciation was created in AWS EBS. We created in us-east-1 which is N-Virginia
        deployment_package: target/test-env.jar #download artifacts from previous job